### ISSUE TITLE
"npm run serve" fails: 'upgrade' of undefined.  "npm run build" succeeds.

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [gtmills/phosphor-webui-vue#84]
This is my first-time attempt at cloning and building this repo.

I'll be grateful for any clues as to why I cannot build the `serve` target, meanwhile the `build` target succeeds.

Below I have included:
1) Error Summary
1) Logs
i) `npm install` log
ii) `npm run serve` log
iii) Debug log

## Error Summary
```
 ERROR  TypeError: Cannot read property 'upgrade' of undefined
TypeError: Cannot read property 'upgrade' of undefined
    at Server.<anonymous> (D:\openBMC\WebUI\phosphor-webui-vue\node_modules\webpack-dev-server\lib\Server.js:134:47)
    at Array.forEach (<anonymous>)
    at new Server (D:\openBMC\WebUI\phosphor-webui-vue\node_modules\webpack-dev-server\lib\Server.js:133:27)
    at serve (D:\openBMC\WebUI\phosphor-webui-vue\node_modules\@vue\cli-service\lib\commands\serve.js:164:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phosphor-webui-vue-prototype@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phosphor-webui-vue-prototype@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2020-01-15T19_21_21_564Z-debug.log
```

## Logs
1) `npm install` log
2) `npm run serve` log
3) Debug log

### `npm install` log
```
$ git clone https://github.com/gtmills/phosphor-webui-vue.git
Cloning into 'phosphor-webui-vue'...
remote: Enumerating objects: 110, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 1338 (delta 56), reused 73 (delta 34), pack-reused 1228R
Receiving objects: 100% (1338/1338), 402.93 KiB | 313.00 KiB/s, done.
Resolving deltas: 100% (717/717), done.

$ cd phosphor-webui-vue/
$ npm install

> yorkie@2.0.0 install D:\openBMC\WebUI\phosphor-webui-vue\node_modules\yorkie
> node bin/install.js

setting up Git hooks
done


> node-sass@4.12.0 install D:\openBMC\WebUI\phosphor-webui-vue\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node
Download complete .] - :
Binary saved to D:\openBMC\WebUI\phosphor-webui-vue\node_modules\node-sass\vendor\win32-x64-64\binding.node
Caching binary to C:\Users\me\AppData\Roaming\npm-cache\node-sass\4.12.0\win32-x64-64_binding.node

> core-js@2.6.11 postinstall D:\openBMC\WebUI\phosphor-webui-vue\node_modules\@babel\runtime-corejs2\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.1 postinstall D:\openBMC\WebUI\phosphor-webui-vue\node_modules\@vue\babel-preset-app\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall D:\openBMC\WebUI\phosphor-webui-vue\node_modules\@vuepress\core\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall D:\openBMC\WebUI\phosphor-webui-vue\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall D:\openBMC\WebUI\phosphor-webui-vue\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> bootstrap-vue@2.1.0 postinstall D:\openBMC\WebUI\phosphor-webui-vue\node_modules\bootstrap-vue
> opencollective || exit 0

                                                             
                          ;iiiiiiiiiiSSSSSSSSiiiiiiiiii;     
                          .rXXXXXXXXXrrrrrrrSXXXXXXXXXr.     
                          :iXXXXXXXX2. ;;;;, r3XXXXXXXi;     
                         ,rSSSSSXXXX2..sSSi: r3XXXSSSSSr,    
                          ,siiiiS2XX2. :;;:,.rXX2Siiiis,     
                           ,riiiii2X2..5XXXi .22iiiiir,      
                            .riiiii22..::::,,r2iiiiir.       
                             .riiiii5SSiiiiS22iiiiir.        
                               ;iiiii5X3333X5iiiii;          
                                :iiiiiSXXXXSiiiii:           
                                 :siiiiSXXSiiiis:            
                                  ,siiiiiiiiiis,             
                                   .riiiiiiiir.              
                                    .riiiiiir.               
                                     .;iiii;.                
                                       ;ii;                  
                                        ::                   

                       Thanks for installing bootstrap-vue 
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 244
                              Number of backers: 60
                              Annual budget: $1,507
                             Current balance: $1,995

          Donate: https://opencollective.com/bootstrap-vue/donate


> core-js@3.3.2 postinstall D:\openBMC\WebUI\phosphor-webui-vue\node_modules\core-js
> node postinstall || echo "ignore"


> node-sass@4.12.0 postinstall D:\openBMC\WebUI\phosphor-webui-vue\node_modules\node-sass
> node scripts/build.js

(node:28272) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
Binary found at D:\openBMC\WebUI\phosphor-webui-vue\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine

> vuepress@1.2.0 postinstall D:\openBMC\WebUI\phosphor-webui-vue\node_modules\vuepress
> opencollective-postinstall || true

Thank you for using vuepress!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/vuepress/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1769 packages from 1136 contributors and audited 939889 packages in 149.697s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

### `npm run serve` log
```
$ npm run serve

> phosphor-webui-vue-prototype@0.1.0 serve D:\openBMC\WebUI\phosphor-webui-vue
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/2 modules 0 active ERROR  TypeError: Cannot read property 'upgrade' of undefined
TypeError: Cannot read property 'upgrade' of undefined
    at Server.<anonymous> (D:\openBMC\WebUI\phosphor-webui-vue\node_modules\webpack-dev-server\lib\Server.js:134:47)
    at Array.forEach (<anonymous>)
    at new Server (D:\openBMC\WebUI\phosphor-webui-vue\node_modules\webpack-dev-server\lib\Server.js:133:27)
    at serve (D:\openBMC\WebUI\phosphor-webui-vue\node_modules\@vue\cli-service\lib\commands\serve.js:164:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phosphor-webui-vue-prototype@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phosphor-webui-vue-prototype@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2020-01-15T19_15_29_673Z-debug.log
```

### Debug Log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle phosphor-webui-vue-prototype@0.1.0~preserve: phosphor-webui-vue-prototype@0.1.0
6 info lifecycle phosphor-webui-vue-prototype@0.1.0~serve: phosphor-webui-vue-prototype@0.1.0
7 verbose lifecycle phosphor-webui-vue-prototype@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle phosphor-webui-vue-prototype@0.1.0~serve: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\openBMC\WebUI\phosphor-webui-vue\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\me\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Java\jre1.8.0_191\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\PuTTY;C:\cygwin64\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Yarn\bin;C:\Program Files\PowerShell\6;C:\Program Files\Microsoft Network Monitor 3;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\me\perl5\bin;C:\Users\me\AppData\Local\Programs\Python\Python36-32\Scripts;C:\Users\me\AppData\Local\Programs\Python\Python36-32;C:\Users\me\AppData\Local\Microsoft\WindowsApps;E:\JViewer-in-Eclipse\VMedia;C:\Users\me\AppData\Roaming\npm;C:\Users\me\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\me\AppData\Local\Yarn\bin;C:\Users\me\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Users\me\AppData\Roaming\Python\Python36\Scripts;C:\Program Files (x86)\Dr. Memory\bin
9 verbose lifecycle phosphor-webui-vue-prototype@0.1.0~serve: CWD: D:\openBMC\WebUI\phosphor-webui-vue
10 silly lifecycle phosphor-webui-vue-prototype@0.1.0~serve: Args: [ '/d /s /c', 'vue-cli-service serve' ]
11 silly lifecycle phosphor-webui-vue-prototype@0.1.0~serve: Returned: code: 1  signal: null
12 info lifecycle phosphor-webui-vue-prototype@0.1.0~serve: Failed to exec serve script
13 verbose stack Error: phosphor-webui-vue-prototype@0.1.0 serve: `vue-cli-service serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid phosphor-webui-vue-prototype@0.1.0
15 verbose cwd D:\openBMC\WebUI\phosphor-webui-vue
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error phosphor-webui-vue-prototype@0.1.0 serve: `vue-cli-service serve`
22 error Exit status 1
23 error Failed at the phosphor-webui-vue-prototype@0.1.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by derick-montague** [comment]
You need to add an `.env.development.local` file to the root directory. It will build and load the login page. If you have a machine, you are trying to run against locally, you need to add the url for that machine.

`BASE_URL="https://<ip or FQDN>"`

I'll add this to the readme. Thanks!
